name: C buiild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: norm
      run: python3 -m pip install norminette && make norm
    - name: make
      run: make
  
  memcheck:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: installing valgrind and timeout
      run: sudo apt-get install autotools-dev debhelper dpatch gdb libc6-dev gcc-multilib libc6-dbg valgrind coreutils
    - name: memcheck
      run: make && bash ./memcheck.sh
