name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: norm
      run: python3 -m pip install norminette && make norm
    - name: make
      run: make
    - name: make test
      run: make test
    - name: memcheck
      run: sudo apt-get install autotools-dev debhelper dpatch gdb libc6-dev gcc-multilib libc6-dbg  && sudo apt-get install valgrind  && make memcheck
